services:
  example-backend:
    image: example-backend
    ports:
      - 127.0.0.1:8080:8080
    restart: unless-stopped
  example-frontend:
    image: example-frontend
    ports:
      - 127.0.0.1:5001:5001
  redis-server:
    image: redis:8.8.0-alpine
